name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
          docker build . --file Dockerfile --tag nginx:$(date +%s)
          docker images
          docker run --name nginx1 -p 80:80 docker.io/library/nginx:$(date +%s)
